# Generated by Django 5.0.2 on 2024-02-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('el', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portaluser',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='portaluser',
            name='qualifications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='portaluser',
            name='real_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
