# Generated by Django 5.0.2 on 2024-02-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('el', '0002_portaluser_bio_portaluser_qualifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portaluser',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
