# Generated by Django 5.0.2 on 2024-02-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('el', '0003_alter_portaluser_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portaluser',
            name='qualifications',
            field=models.TextField(blank=True, null=True),
        ),
    ]
