# Generated by Django 5.0.2 on 2024-03-06 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('el', '0010_chatgroup_chatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatgroup',
            name='members',
        ),
    ]
