# Generated by Django 5.0.2 on 2024-03-08 04:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('el', '0014_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notificationtype',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
