# Generated by Django 5.0.2 on 2024-02-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('el', '0002_course_subject_enrollment_date_enrolled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portaluser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='portaluser_set', related_query_name='portaluser', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='portaluser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='portaluser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='portaluser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='portaluser_set', related_query_name='portaluser', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='portaluser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='portaluser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
