# Generated by Django 5.0.2 on 2024-02-21 18:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('el', '0004_alter_portaluser_options_alter_portaluser_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatgroup',
            old_name='user',
            new_name='creator',
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='chat_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
